command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: SERVING_ENDPOINT
    value: "databricks-llama-4-maverick"
  - name: GENIE_ID
    value: "01f0ea25e2fb1ec38503f948b662ca19"